/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    administrators: AdministratorAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    administrators: Administrator;
    customers: Customer;
    orders: Order;
    products: Product;
    productCategories: ProductCategory;
    productSubCategories: ProductSubCategory;
    productReviews: ProductReview;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      orders: 'orders';
    };
    productCategories: {
      subcategories: 'productSubCategories';
      products: 'products';
    };
    productSubCategories: {
      products: 'products';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    administrators: AdministratorsSelect<false> | AdministratorsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    productCategories: ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    productSubCategories: ProductSubCategoriesSelect<false> | ProductSubCategoriesSelect<true>;
    productReviews: ProductReviewsSelect<false> | ProductReviewsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    emailMessages: EmailMessage;
    shopSettings: ShopSetting;
    shopLayout: ShopLayout;
    'inpost-pickup': InpostPickup;
    'inpost-courier': InpostCourier;
    'inpost-courier-cod': InpostCourierCod;
    paywalls: Paywall;
    fulfilment: Fulfilment;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    emailMessages: EmailMessagesSelect<false> | EmailMessagesSelect<true>;
    shopSettings: ShopSettingsSelect<false> | ShopSettingsSelect<true>;
    shopLayout: ShopLayoutSelect<false> | ShopLayoutSelect<true>;
    'inpost-pickup': InpostPickupSelect<false> | InpostPickupSelect<true>;
    'inpost-courier': InpostCourierSelect<false> | InpostCourierSelect<true>;
    'inpost-courier-cod': InpostCourierCodSelect<false> | InpostCourierCodSelect<true>;
    paywalls: PaywallsSelect<false> | PaywallsSelect<true>;
    fulfilment: FulfilmentSelect<false> | FulfilmentSelect<true>;
  };
  locale: 'en' | 'pl';
  user:
    | (Administrator & {
        collection: 'administrators';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface AdministratorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
    reversed?: boolean | null;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | CarouselBlock
    | AccordionBlock
    | HotspotBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | Administrator)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "administrators".
 */
export interface Administrator {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  spacingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  spacingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneSixth' | 'oneThird' | 'half' | 'twoThirds' | 'fiveSixth' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        enableProse?: boolean | null;
        paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
        paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        background?: string | null;
        id?: string | null;
      }[]
    | null;
  alignment?: ('center' | 'left' | 'right' | 'full') | null;
  spacingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  spacingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  radius?: boolean | null;
  specifiedRadius?: boolean | null;
  radiusAll?:
    | (
        | 'rounded-none'
        | 'rounded-sm'
        | 'rounded-md'
        | 'rounded-lg'
        | 'rounded-xl'
        | 'rounded-2xl'
        | 'rounded-3xl'
        | 'rounded-full'
      )
    | null;
  radiusTopLeft?:
    | (
        | 'rounded-tl-none'
        | 'rounded-tl-sm'
        | 'rounded-tl-md'
        | 'rounded-tl-lg'
        | 'rounded-tl-xl'
        | 'rounded-tl-2xl'
        | 'rounded-tl-3xl'
        | 'rounded-tl-full'
      )
    | null;
  radiusTopRight?:
    | (
        | 'rounded-tr-none'
        | 'rounded-tr-sm'
        | 'rounded-tr-md'
        | 'rounded-tr-lg'
        | 'rounded-tr-xl'
        | 'rounded-tr-2xl'
        | 'rounded-tr-3xl'
        | 'rounded-tr-full'
      )
    | null;
  radiusBottomLeft?:
    | (
        | 'rounded-bl-none'
        | 'rounded-bl-sm'
        | 'rounded-bl-md'
        | 'rounded-bl-lg'
        | 'rounded-bl-xl'
        | 'rounded-bl-2xl'
        | 'rounded-bl-3xl'
        | 'rounded-bl-full'
      )
    | null;
  radiusBottomRight?:
    | (
        | 'rounded-br-none'
        | 'rounded-br-sm'
        | 'rounded-br-md'
        | 'rounded-br-lg'
        | 'rounded-br-xl'
        | 'rounded-br-2xl'
        | 'rounded-br-3xl'
        | 'rounded-br-full'
      )
    | null;
  background?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  spacingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  spacingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  type: 'default' | 'logo';
  title?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slides?:
    | {
        image: number | Media;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  autoplay?: number | null;
  spacingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  spacingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  items: {
    title: string;
    content: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    id?: string | null;
  }[];
  spacingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  spacingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotspotBlock".
 */
export interface HotspotBlock {
  title?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  type: 'category' | 'subcategory' | 'manual';
  appearance: 'default' | 'slider' | 'sliderLoop';
  category?: (number | null) | ProductCategory;
  subcategory?: (number | null) | ProductSubCategory;
  /**
   * Sort is applied only when type is set to 'category' or 'subcategory', in manual mode you can manually sort products in the list
   */
  sort?:
    | (
        | '-bought'
        | '-createdAt'
        | 'createdAt'
        | 'variants.pricing[0].value,pricing.value'
        | '-variants.pricing[0].value,-pricing.value'
      )
    | null;
  /**
   * Products order will be the same as the order of selection
   */
  products?: (number | Product)[] | null;
  limit?: number | null;
  spacingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  spacingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingBottom?: ('none' | 'small' | 'medium' | 'large') | null;
  paddingTop?: ('none' | 'small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hotspotZone';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  subcategories?: {
    docs?: (number | ProductSubCategory)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productSubCategories".
 */
export interface ProductSubCategory {
  id: number;
  category: number | ProductCategory;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  products?: {
    docs?: (number | Product)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * If you have variants, first image will be variant image.
   */
  images: (number | Media)[];
  details?:
    | {
        title: string;
        content: {
          root: {
            type: string;
            children: {
              type: string;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  enableVariants?: boolean | null;
  /**
   * If false, price is in Product Details
   */
  enableVariantPrices?: boolean | null;
  /**
   * If false, weight is in Product Details
   */
  enableVariantWeights?: boolean | null;
  variantsType?: ('sizes' | 'colors' | 'colorsAndSizes') | null;
  colors?:
    | {
        label: string;
        slug: string;
        colorValue?: string | null;
        id?: string | null;
      }[]
    | null;
  sizes?:
    | {
        label: string;
        slug: string;
        id?: string | null;
      }[]
    | null;
  variants?:
    | {
        size?: string | null;
        color?: string | null;
        variantSlug?: string | null;
        image?: (number | null) | Media;
        /**
         * Define stock for this variant. A stock of 0 disables checkout for this variant.
         */
        stock: number;
        /**
         * Define weight for this variant.
         */
        weight?: number | null;
        pricing?:
          | {
              value: number;
              currency: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  categoriesArr?:
    | {
        category: number | ProductCategory;
        subcategories?: (number | ProductSubCategory)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Define stock for whole product. A stock of 0 disables checkout for this product.
   */
  stock?: number | null;
  /**
   * Define weight for whole product.
   */
  weight?: number | null;
  pricing?:
    | {
        value: number;
        currency: string;
        id?: string | null;
      }[]
    | null;
  bought?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  fullName?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  birthDate?: string | null;
  lastBuyerType?: ('individual' | 'company') | null;
  shippings?:
    | {
        name: string;
        address: string;
        city: string;
        country:
          | 'ad'
          | 'al'
          | 'at'
          | 'ba'
          | 'be'
          | 'bg'
          | 'by'
          | 'ch'
          | 'cy'
          | 'cz'
          | 'de'
          | 'dk'
          | 'ee'
          | 'es'
          | 'fi'
          | 'fr'
          | 'gb'
          | 'gr'
          | 'hr'
          | 'hu'
          | 'ie'
          | 'is'
          | 'it'
          | 'li'
          | 'lt'
          | 'lu'
          | 'lv'
          | 'mc'
          | 'md'
          | 'me'
          | 'mk'
          | 'mt'
          | 'nl'
          | 'no'
          | 'pl'
          | 'pt'
          | 'ro'
          | 'rs'
          | 'ru'
          | 'se'
          | 'si'
          | 'sk'
          | 'sm'
          | 'ua'
          | 'va';
        region: string;
        postalCode: string;
        phone: string;
        email: string;
        default?: boolean | null;
        id?: string | null;
      }[]
    | null;
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  wishlist?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  customer?: (number | null) | Customer;
  date?: string | null;
  extractedFromStock?: boolean | null;
  products?:
    | {
        product?: (number | null) | Product;
        productName?: string | null;
        isFromAPI: boolean;
        color?: string | null;
        size?: string | null;
        variantSlug?: string | null;
        quantity: number;
        price?: number | null;
        autoprice?: boolean | null;
        priceTotal: number;
        id?: string | null;
      }[]
    | null;
  invoice?: {
    isCompany?: boolean | null;
    name?: string | null;
    tin?: string | null;
    address?: string | null;
    city?: string | null;
    country?:
      | (
          | 'ad'
          | 'al'
          | 'at'
          | 'ba'
          | 'be'
          | 'bg'
          | 'by'
          | 'ch'
          | 'cy'
          | 'cz'
          | 'de'
          | 'dk'
          | 'ee'
          | 'es'
          | 'fi'
          | 'fr'
          | 'gb'
          | 'gr'
          | 'hr'
          | 'hu'
          | 'ie'
          | 'is'
          | 'it'
          | 'li'
          | 'lt'
          | 'lu'
          | 'lv'
          | 'mc'
          | 'md'
          | 'me'
          | 'mk'
          | 'mt'
          | 'nl'
          | 'no'
          | 'pl'
          | 'pt'
          | 'ro'
          | 'rs'
          | 'ru'
          | 'se'
          | 'si'
          | 'sk'
          | 'sm'
          | 'ua'
          | 'va'
        )
      | null;
    region?: string | null;
    postalCode?: string | null;
  };
  printLabel?: {
    packageNumber?: string | null;
    width?: number | null;
    height?: number | null;
    length?: number | null;
    weight?: number | null;
    dimension?: string | null;
  };
  shippingAddress: {
    name: string;
    address: string;
    pickupPointID?: string | null;
    pickupPointAddress?: string | null;
    city: string;
    country:
      | 'ad'
      | 'al'
      | 'at'
      | 'ba'
      | 'be'
      | 'bg'
      | 'by'
      | 'ch'
      | 'cy'
      | 'cz'
      | 'de'
      | 'dk'
      | 'ee'
      | 'es'
      | 'fi'
      | 'fr'
      | 'gb'
      | 'gr'
      | 'hr'
      | 'hu'
      | 'ie'
      | 'is'
      | 'it'
      | 'li'
      | 'lt'
      | 'lu'
      | 'lv'
      | 'mc'
      | 'md'
      | 'me'
      | 'mk'
      | 'mt'
      | 'nl'
      | 'no'
      | 'pl'
      | 'pt'
      | 'ro'
      | 'rs'
      | 'ru'
      | 'se'
      | 'si'
      | 'sk'
      | 'sm'
      | 'ua'
      | 'va';
    region: string;
    postalCode: string;
    email: string;
    phone: string;
  };
  orderDetails: {
    total: number;
    shippingCost: number;
    totalWithShipping: number;
    currency: string;
    amountPaid?: number | null;
    shipping?: ('inpost-pickup' | 'inpost-courier' | 'inpost-courier-cod') | null;
    transactionID?: string | null;
    status: 'pending' | 'paid' | 'unpaid' | 'processing' | 'shipped' | 'completed' | 'cancelled' | 'returned';
    shippingDate?: string | null;
    trackingNumber?: string | null;
    orderNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productReviews".
 */
export interface ProductReview {
  id: number;
  product: number | Product;
  author: number | Customer;
  rating: number;
  review?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        id?: string | null;
        title?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'administrators';
        value: number | Administrator;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'productCategories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'productSubCategories';
        value: number | ProductSubCategory;
      } | null)
    | ({
        relationTo: 'productReviews';
        value: number | ProductReview;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-jobs';
        value: number | PayloadJob;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'administrators';
        value: number | Administrator;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'administrators';
        value: number | Administrator;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
        reversed?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        hotspotZone?: T | HotspotBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  spacingBottom?: T;
  spacingTop?: T;
  paddingBottom?: T;
  paddingTop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        enableProse?: T;
        paddingBottom?: T;
        paddingTop?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        background?: T;
        id?: T;
      };
  alignment?: T;
  spacingBottom?: T;
  spacingTop?: T;
  paddingBottom?: T;
  paddingTop?: T;
  radius?: T;
  specifiedRadius?: T;
  radiusAll?: T;
  radiusTopLeft?: T;
  radiusTopRight?: T;
  radiusBottomLeft?: T;
  radiusBottomRight?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  spacingBottom?: T;
  spacingTop?: T;
  paddingBottom?: T;
  paddingTop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  slides?:
    | T
    | {
        image?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  autoplay?: T;
  spacingBottom?: T;
  spacingTop?: T;
  paddingBottom?: T;
  paddingTop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  spacingBottom?: T;
  spacingTop?: T;
  paddingBottom?: T;
  paddingTop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hotspotBlock_select".
 */
export interface HotspotBlockSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  appearance?: T;
  category?: T;
  subcategory?: T;
  sort?: T;
  products?: T;
  limit?: T;
  spacingBottom?: T;
  spacingTop?: T;
  paddingBottom?: T;
  paddingTop?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "administrators_select".
 */
export interface AdministratorsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  fullName?: T;
  firstName?: T;
  lastName?: T;
  birthDate?: T;
  lastBuyerType?: T;
  shippings?:
    | T
    | {
        name?: T;
        address?: T;
        city?: T;
        country?: T;
        region?: T;
        postalCode?: T;
        phone?: T;
        email?: T;
        default?: T;
        id?: T;
      };
  orders?: T;
  cart?: T;
  wishlist?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  id?: T;
  customer?: T;
  date?: T;
  extractedFromStock?: T;
  products?:
    | T
    | {
        product?: T;
        productName?: T;
        isFromAPI?: T;
        color?: T;
        size?: T;
        variantSlug?: T;
        quantity?: T;
        price?: T;
        autoprice?: T;
        priceTotal?: T;
        id?: T;
      };
  invoice?:
    | T
    | {
        isCompany?: T;
        name?: T;
        tin?: T;
        address?: T;
        city?: T;
        country?: T;
        region?: T;
        postalCode?: T;
      };
  printLabel?:
    | T
    | {
        packageNumber?: T;
        width?: T;
        height?: T;
        length?: T;
        weight?: T;
        dimension?: T;
      };
  shippingAddress?:
    | T
    | {
        name?: T;
        address?: T;
        pickupPointID?: T;
        pickupPointAddress?: T;
        city?: T;
        country?: T;
        region?: T;
        postalCode?: T;
        email?: T;
        phone?: T;
      };
  orderDetails?:
    | T
    | {
        total?: T;
        shippingCost?: T;
        totalWithShipping?: T;
        currency?: T;
        amountPaid?: T;
        shipping?: T;
        transactionID?: T;
        status?: T;
        shippingDate?: T;
        trackingNumber?: T;
        orderNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  description?: T;
  images?: T;
  details?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  enableVariants?: T;
  enableVariantPrices?: T;
  enableVariantWeights?: T;
  variantsType?: T;
  colors?:
    | T
    | {
        label?: T;
        slug?: T;
        colorValue?: T;
        id?: T;
      };
  sizes?:
    | T
    | {
        label?: T;
        slug?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        size?: T;
        color?: T;
        variantSlug?: T;
        image?: T;
        stock?: T;
        weight?: T;
        pricing?:
          | T
          | {
              value?: T;
              currency?: T;
              id?: T;
            };
        id?: T;
      };
  categoriesArr?:
    | T
    | {
        category?: T;
        subcategories?: T;
        id?: T;
      };
  stock?: T;
  weight?: T;
  pricing?:
    | T
    | {
        value?: T;
        currency?: T;
        id?: T;
      };
  bought?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productCategories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slugLock?: T;
  subcategories?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productSubCategories_select".
 */
export interface ProductSubCategoriesSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productReviews_select".
 */
export interface ProductReviewsSelect<T extends boolean = true> {
  product?: T;
  author?: T;
  rating?: T;
  review?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        id?: T;
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  type: 'default' | 'floating';
  logo?: (number | null) | Media;
  hideOnScroll?: boolean | null;
  background?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  attribution?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailMessages".
 */
export interface EmailMessage {
  id: number;
  smtp: {
    host: string;
    port: number;
    secure: boolean;
    user: string;
    password: string;
    fromEmail: string;
  };
  messages: {
    logo?: (number | null) | Media;
    additionalText?: string | null;
    template: 'default';
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopSettings".
 */
export interface ShopSetting {
  id: number;
  /**
   * First currency is the default one
   */
  availableCurrencies: ('USD' | 'EUR' | 'GBP' | 'PLN')[];
  currencyValues?:
    | {
        currency: string;
        value: number;
        id?: string | null;
      }[]
    | null;
  enableOAuth: boolean;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopLayout".
 */
export interface ShopLayout {
  id: number;
  productDetails: {
    type: 'WithImageGalleryExpandableDetails';
    reviewsEnabled: boolean;
  };
  productList: {
    filters: 'none' | 'withSidebar' | 'sortOnly';
  };
  cartAndWishlist: {
    type: 'slideOver';
  };
  checkout: {
    type: 'OneStepWithSummary';
  };
  clientPanel: {
    type: 'withSidebar';
    help: {
      title: string;
      content: {
        root: {
          type: string;
          children: {
            type: string;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      };
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inpost-pickup".
 */
export interface InpostPickup {
  id: number;
  enabled?: boolean | null;
  settings: {
    label: string;
    /**
     * You can provide typical delivery time or any other information
     */
    description?: string | null;
  };
  deliveryZones?:
    | {
        countries: (
          | 'ad'
          | 'al'
          | 'at'
          | 'ba'
          | 'be'
          | 'bg'
          | 'by'
          | 'ch'
          | 'cy'
          | 'cz'
          | 'de'
          | 'dk'
          | 'ee'
          | 'es'
          | 'fi'
          | 'fr'
          | 'gb'
          | 'gr'
          | 'hr'
          | 'hu'
          | 'ie'
          | 'is'
          | 'it'
          | 'li'
          | 'lt'
          | 'lu'
          | 'lv'
          | 'mc'
          | 'md'
          | 'me'
          | 'mk'
          | 'mt'
          | 'nl'
          | 'no'
          | 'pl'
          | 'pt'
          | 'ro'
          | 'rs'
          | 'ru'
          | 'se'
          | 'si'
          | 'sk'
          | 'sm'
          | 'ua'
          | 'va'
        )[];
        freeShipping?:
          | {
              value: number;
              currency: string;
              id?: string | null;
            }[]
          | null;
        range?:
          | {
              weightFrom: number;
              weightTo: number;
              pricing: {
                value: number;
                currency: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  icon?: (number | null) | Media;
  clientId?: string | null;
  /**
   * Remember to pass matching keys for choosen environment
   */
  APIUrl?: ('https://api-shipx-pl.easypack24.net' | 'https://sandbox-api-shipx-pl.easypack24.net') | null;
  shipXAPIKey?: string | null;
  geowidgetToken?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inpost-courier".
 */
export interface InpostCourier {
  id: number;
  enabled?: boolean | null;
  settings: {
    label: string;
    /**
     * You can provide typical delivery time or any other information
     */
    description?: string | null;
  };
  deliveryZones?:
    | {
        countries: (
          | 'ad'
          | 'al'
          | 'at'
          | 'ba'
          | 'be'
          | 'bg'
          | 'by'
          | 'ch'
          | 'cy'
          | 'cz'
          | 'de'
          | 'dk'
          | 'ee'
          | 'es'
          | 'fi'
          | 'fr'
          | 'gb'
          | 'gr'
          | 'hr'
          | 'hu'
          | 'ie'
          | 'is'
          | 'it'
          | 'li'
          | 'lt'
          | 'lu'
          | 'lv'
          | 'mc'
          | 'md'
          | 'me'
          | 'mk'
          | 'mt'
          | 'nl'
          | 'no'
          | 'pl'
          | 'pt'
          | 'ro'
          | 'rs'
          | 'ru'
          | 'se'
          | 'si'
          | 'sk'
          | 'sm'
          | 'ua'
          | 'va'
        )[];
        freeShipping?:
          | {
              value: number;
              currency: string;
              id?: string | null;
            }[]
          | null;
        range?:
          | {
              weightFrom: number;
              weightTo: number;
              pricing: {
                value: number;
                currency: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  icon?: (number | null) | Media;
  clientId?: string | null;
  /**
   * Remember to pass matching keys for choosen environment
   */
  APIUrl?: ('https://api-shipx-pl.easypack24.net' | 'https://sandbox-api-shipx-pl.easypack24.net') | null;
  shipXAPIKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inpost-courier-cod".
 */
export interface InpostCourierCod {
  id: number;
  enabled?: boolean | null;
  settings: {
    label: string;
    /**
     * You can provide typical delivery time or any other information
     */
    description?: string | null;
  };
  deliveryZones?:
    | {
        countries: (
          | 'ad'
          | 'al'
          | 'at'
          | 'ba'
          | 'be'
          | 'bg'
          | 'by'
          | 'ch'
          | 'cy'
          | 'cz'
          | 'de'
          | 'dk'
          | 'ee'
          | 'es'
          | 'fi'
          | 'fr'
          | 'gb'
          | 'gr'
          | 'hr'
          | 'hu'
          | 'ie'
          | 'is'
          | 'it'
          | 'li'
          | 'lt'
          | 'lu'
          | 'lv'
          | 'mc'
          | 'md'
          | 'me'
          | 'mk'
          | 'mt'
          | 'nl'
          | 'no'
          | 'pl'
          | 'pt'
          | 'ro'
          | 'rs'
          | 'ru'
          | 'se'
          | 'si'
          | 'sk'
          | 'sm'
          | 'ua'
          | 'va'
        )[];
        freeShipping?:
          | {
              value: number;
              currency: string;
              id?: string | null;
            }[]
          | null;
        range?:
          | {
              weightFrom: number;
              weightTo: number;
              pricing: {
                value: number;
                currency: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  icon?: (number | null) | Media;
  clientId?: string | null;
  /**
   * Remember to pass matching keys for choosen environment
   */
  APIUrl?: ('https://api-shipx-pl.easypack24.net' | 'https://sandbox-api-shipx-pl.easypack24.net') | null;
  shipXAPIKey?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paywalls".
 */
export interface Paywall {
  id: number;
  paywall: 'stripe' | 'autopay' | 'p24';
  /**
   * If you want to use test environment, you can also provide test keys here.
   */
  stripe?: {
    secret: string;
    webhookSecret: string;
    public?: string | null;
  };
  /**
   * If you want to use test environment, you can also provide test keys here.
   */
  autopay?: {
    serviceID: string;
    hashKey: string;
    endpoint: string;
  };
  /**
   * If you want to use test environment, you can also provide test keys here.
   */
  p24?: {
    posId: string;
    crc: string;
    secretId: string;
    endpoint: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fulfilment".
 */
export interface Fulfilment {
  id: number;
  shopAddress: {
    name: string;
    address: string;
    city: string;
    country:
      | 'ad'
      | 'al'
      | 'at'
      | 'ba'
      | 'be'
      | 'bg'
      | 'by'
      | 'ch'
      | 'cy'
      | 'cz'
      | 'de'
      | 'dk'
      | 'ee'
      | 'es'
      | 'fi'
      | 'fr'
      | 'gb'
      | 'gr'
      | 'hr'
      | 'hu'
      | 'ie'
      | 'is'
      | 'it'
      | 'li'
      | 'lt'
      | 'lu'
      | 'lv'
      | 'mc'
      | 'md'
      | 'me'
      | 'mk'
      | 'mt'
      | 'nl'
      | 'no'
      | 'pl'
      | 'pt'
      | 'ro'
      | 'rs'
      | 'ru'
      | 'se'
      | 'si'
      | 'sk'
      | 'sm'
      | 'ua'
      | 'va';
    region: string;
    postalCode: string;
    email: string;
    phone: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  type?: T;
  logo?: T;
  hideOnScroll?: T;
  background?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  attribution?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emailMessages_select".
 */
export interface EmailMessagesSelect<T extends boolean = true> {
  smtp?:
    | T
    | {
        host?: T;
        port?: T;
        secure?: T;
        user?: T;
        password?: T;
        fromEmail?: T;
      };
  messages?:
    | T
    | {
        logo?: T;
        additionalText?: T;
        template?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopSettings_select".
 */
export interface ShopSettingsSelect<T extends boolean = true> {
  availableCurrencies?: T;
  currencyValues?:
    | T
    | {
        currency?: T;
        value?: T;
        id?: T;
      };
  enableOAuth?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopLayout_select".
 */
export interface ShopLayoutSelect<T extends boolean = true> {
  productDetails?:
    | T
    | {
        type?: T;
        reviewsEnabled?: T;
      };
  productList?:
    | T
    | {
        filters?: T;
      };
  cartAndWishlist?:
    | T
    | {
        type?: T;
      };
  checkout?:
    | T
    | {
        type?: T;
      };
  clientPanel?:
    | T
    | {
        type?: T;
        help?:
          | T
          | {
              title?: T;
              content?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inpost-pickup_select".
 */
export interface InpostPickupSelect<T extends boolean = true> {
  enabled?: T;
  settings?:
    | T
    | {
        label?: T;
        description?: T;
      };
  deliveryZones?:
    | T
    | {
        countries?: T;
        freeShipping?:
          | T
          | {
              value?: T;
              currency?: T;
              id?: T;
            };
        range?:
          | T
          | {
              weightFrom?: T;
              weightTo?: T;
              pricing?:
                | T
                | {
                    value?: T;
                    currency?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  icon?: T;
  clientId?: T;
  APIUrl?: T;
  shipXAPIKey?: T;
  geowidgetToken?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inpost-courier_select".
 */
export interface InpostCourierSelect<T extends boolean = true> {
  enabled?: T;
  settings?:
    | T
    | {
        label?: T;
        description?: T;
      };
  deliveryZones?:
    | T
    | {
        countries?: T;
        freeShipping?:
          | T
          | {
              value?: T;
              currency?: T;
              id?: T;
            };
        range?:
          | T
          | {
              weightFrom?: T;
              weightTo?: T;
              pricing?:
                | T
                | {
                    value?: T;
                    currency?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  icon?: T;
  clientId?: T;
  APIUrl?: T;
  shipXAPIKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inpost-courier-cod_select".
 */
export interface InpostCourierCodSelect<T extends boolean = true> {
  enabled?: T;
  settings?:
    | T
    | {
        label?: T;
        description?: T;
      };
  deliveryZones?:
    | T
    | {
        countries?: T;
        freeShipping?:
          | T
          | {
              value?: T;
              currency?: T;
              id?: T;
            };
        range?:
          | T
          | {
              weightFrom?: T;
              weightTo?: T;
              pricing?:
                | T
                | {
                    value?: T;
                    currency?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  icon?: T;
  clientId?: T;
  APIUrl?: T;
  shipXAPIKey?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paywalls_select".
 */
export interface PaywallsSelect<T extends boolean = true> {
  paywall?: T;
  stripe?:
    | T
    | {
        secret?: T;
        webhookSecret?: T;
        public?: T;
      };
  autopay?:
    | T
    | {
        serviceID?: T;
        hashKey?: T;
        endpoint?: T;
      };
  p24?:
    | T
    | {
        posId?: T;
        crc?: T;
        secretId?: T;
        endpoint?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fulfilment_select".
 */
export interface FulfilmentSelect<T extends boolean = true> {
  shopAddress?:
    | T
    | {
        name?: T;
        address?: T;
        city?: T;
        country?: T;
        region?: T;
        postalCode?: T;
        email?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null);
    global?: string | null;
    user?: (number | null) | Administrator;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}